/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package makepizza;

import java.util.ArrayList;
import java.util.InputMismatchException;
import java.util.Scanner;
import java.util.jar.Attributes.Name;
import javax.swing.JOptionPane;


public class Machine extends javax.swing.JFrame {
  static  PIZZA pizza= new PIZZA();
  static  Pan pan= new Pan();
  static  Dough dough= new Dough();


  static  Ingrediance cheese =new Ingrediance();
   static Ingrediance salt =new Ingrediance();
  static  Ingrediance flour =new Ingrediance();
  static  Ingrediance yeast =new Ingrediance();
  static  Ingrediance Tomatoes =new Ingrediance();
static    Ingrediance Garilic =new Ingrediance();
  static  Ingrediance onion =new Ingrediance();
  static  Ingrediance Sause =new Ingrediance();
static    Ingrediance cOregano =new Ingrediance();

    
    
    
    
    
    public Machine() {
        
this.setTitle("My Pizza");
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cheesee = new javax.swing.JTextField();
        saltt = new javax.swing.JTextField();
        flourr = new javax.swing.JTextField();
        yeastt = new javax.swing.JTextField();
        tomatoess = new javax.swing.JTextField();
        gralicc = new javax.swing.JTextField();
        onionn = new javax.swing.JTextField();
        sausee = new javax.swing.JTextField();
        oreganoo = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        pansize = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jTextField12 = new javax.swing.JTextField();
        sizee = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        panin = new javax.swing.JPanel();
        cheesee1 = new javax.swing.JTextField();
        saltt1 = new javax.swing.JTextField();
        flourr1 = new javax.swing.JTextField();
        yeastt1 = new javax.swing.JTextField();
        tomatoess1 = new javax.swing.JTextField();
        oreganoo1 = new javax.swing.JTextField();
        sausee1 = new javax.swing.JTextField();
        onionn1 = new javax.swing.JTextField();
        gralicc1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        sizee1 = new javax.swing.JComboBox<>();
        sizee2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(255, 0, 0));
        jTabbedPane1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 255));
        jLabel1.setText("Adding The Weight's Ingredients");

        cheesee.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cheesee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cheesee.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Cheese", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        cheesee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheeseeActionPerformed(evt);
            }
        });

        saltt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        saltt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        saltt.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Salt", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        flourr.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        flourr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        flourr.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Flour", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        yeastt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        yeastt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        yeastt.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Yeast", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        tomatoess.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tomatoess.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tomatoess.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Tomatoes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        gralicc.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        gralicc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gralicc.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Garilic", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        onionn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        onionn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        onionn.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Onion", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        sausee.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        sausee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sausee.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Sause", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        oreganoo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        oreganoo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        oreganoo.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Oregano", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        add.setBackground(new java.awt.Color(51, 255, 51));
        add.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        add.setForeground(new java.awt.Color(51, 51, 255));
        add.setText("Add Ingredient");
        add.setBorderPainted(false);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        pansize.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        pansize.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pansize.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Pan Size", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        pansize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pansizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(yeastt, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(flourr, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(108, 108, 108)
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(onionn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sausee, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(oreganoo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(saltt, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(326, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tomatoess, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cheesee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(gralicc, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(pansize, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cheesee, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gralicc, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saltt, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(onionn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flourr, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sausee, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yeastt, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oreganoo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tomatoess, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pansize, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(318, 318, 318))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 850, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Machine", jPanel1);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Request Pizza", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(255, 0, 0))); // NOI18N

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 204));
        jButton2.setText("Request");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField12.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Capacity", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        sizee.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        sizee.setForeground(new java.awt.Color(255, 0, 0));
        sizee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Small", "Meduim", "Large" }));
        sizee.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Pizza SIze", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        sizee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeeActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 10)); // NOI18N
        jButton4.setText("Calculate Calories");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175)
                .addComponent(sizee, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 330, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(88, 88, 88))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sizee, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("User", jPanel2);

        panin.setBackground(new java.awt.Color(255, 255, 255));
        panin.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Customer", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        panin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cheesee1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cheesee1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Cheese", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        cheesee1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheesee1ActionPerformed(evt);
            }
        });
        panin.add(cheesee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 21, 113, 51));

        saltt1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        saltt1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Salt", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        panin.add(saltt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 104, 113, 56));

        flourr1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        flourr1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Flour", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        panin.add(flourr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 215, 113, 57));

        yeastt1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        yeastt1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Yeast", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        panin.add(yeastt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 342, 117, 59));

        tomatoess1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tomatoess1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Tomatoes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        panin.add(tomatoess1, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 440, 128, 60));

        oreganoo1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        oreganoo1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Oregano", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        panin.add(oreganoo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 342, 132, 59));

        sausee1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        sausee1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Sause", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        panin.add(sausee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 215, 121, 57));

        onionn1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        onionn1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Onion", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        panin.add(onionn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 104, 118, 56));

        gralicc1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        gralicc1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Garilic", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        panin.add(gralicc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 21, 123, 51));

        jButton1.setBackground(new java.awt.Color(51, 255, 51));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("cook");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panin.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 95, 51));

        sizee1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        sizee1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Small", "Meduim", "Large" }));
        sizee1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Pizza Size", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        panin.add(sizee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 553, 128, -1));

        sizee2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        sizee2.setForeground(new java.awt.Color(255, 0, 0));
        sizee2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Small", "Meduim", "Large" }));
        sizee2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Pan  SIze", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        panin.add(sizee2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 550, 170, 50));
        sizee2.getAccessibleContext().setAccessibleName("pan");
        sizee2.getAccessibleContext().setAccessibleParent(pansize);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(panin, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(panin, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab("Pan", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String nomber  = jTextField12.getText();

        String size=sizee.getSelectedItem().toString();
        if("Small".equals(size))
        {
            if(Integer.parseInt(nomber)<=pizza.getsmall())
            { pizza.setsmall(pizza.getsmall()-Integer.parseInt(nomber));
         JOptionPane.showMessageDialog(null,"Request Sent", "ok", JOptionPane.OK_OPTION); }  
            else
                JOptionPane.showMessageDialog(null,"not enougth.", "Warning", JOptionPane.ERROR_MESSAGE);
        }
        if("Meduim".equals(size)){
  if(Integer.parseInt(nomber)<=pizza.getmeduim())
  {   pizza.setmeduim(pizza.getmeduim()-Integer.parseInt(nomber));
  JOptionPane.showMessageDialog(null,"Request Sent", "ok", JOptionPane.OK_OPTION);
  }  
  else

      JOptionPane.showMessageDialog(null,"not enougth.", "Warning", JOptionPane.ERROR_MESSAGE);
        }
        if("Large".equals(size)){
  if(Integer.parseInt(nomber)<=pizza.gettlarge())
  {    pizza.setlarge(pizza.gettlarge()-Integer.parseInt(nomber)); 
  JOptionPane.showMessageDialog(null,"Request Sent", "ok", JOptionPane.OK_OPTION); } 
  else 
      JOptionPane.showMessageDialog(null,"not enougth.", "Warning", JOptionPane.ERROR_MESSAGE);
        }
      
  
      
     
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
       
        String textT1 = cheesee.getText();
        String textT2 = saltt.getText();

        String textT3 = flourr.getText();
        String textT4 = yeastt.getText();
        String textT5 = tomatoess.getText();
        String textT6 = gralicc.getText();
        String textT7 = onionn.getText();
        String textT8 = sausee.getText();
        String textT9 = oreganoo.getText();
        String textT10 = pansize.getText();
        pan.setSize(textT10);
        cheese.setWeight(Double.parseDouble(textT1));
        salt.setWeight(Double.parseDouble(textT2));
        flour.setWeight(Double.parseDouble(textT3));
        yeast.setWeight(Double.parseDouble(textT4));
        Tomatoes.setWeight(Double.parseDouble(textT5));
        Garilic.setWeight(Double.parseDouble(textT6));
        onion.setWeight(Double.parseDouble(textT7));
        Sause.setWeight(Double.parseDouble(textT8));
        cOregano.setWeight(Double.parseDouble(textT9));
        System.out.println( Garilic.getWeight());
        JOptionPane.showMessageDialog(null,"Ingrediants added succecfully \n go to pan interface to cook pizza \n ");
      
    }//GEN-LAST:event_addActionPerformed

    private void cheeseeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheeseeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cheeseeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String textT1 = cheesee1.getText();
        String textT2 = saltt1.getText();
        String textT3 = flourr1.getText();
        String textT4 = yeastt1.getText();
        String textT5 = tomatoess1.getText();
        String textT6 = gralicc1.getText();
        String textT7 = onionn1.getText();
        String textT8 = sausee1.getText();
        String textT9 = oreganoo1.getText();String nomber  = jTextField12.getText();
      
        String size=sizee.getSelectedItem().toString();//size of pizza
        
        //count size of pan
       double pansizing=Double.parseDouble(textT1)+ Double.parseDouble(textT2)+ Double.parseDouble(textT3)+  Double.parseDouble(textT4)+Double.parseDouble(textT5)+Double.parseDouble(textT6)+Double.parseDouble(textT7)+Double.parseDouble(textT8)+Double.parseDouble(textT9);
        boolean check=false;
        if(cheese.getWeight()> Double.parseDouble(textT1)){
            if(salt.getWeight()>Double.parseDouble(textT2)){
                if(flour.getWeight()>Double.parseDouble(textT3)){
                    if(yeast.getWeight()>Double.parseDouble(textT4)){
                        if(Tomatoes.getWeight()>Double.parseDouble(textT5)){
                            if(Garilic.getWeight()>Double.parseDouble(textT6)){
                                if(onion.getWeight()>Double.parseDouble(textT7)){
                                    if(Sause.getWeight()>Double.parseDouble(textT8)){
                                        if(cOregano.getWeight()>Double.parseDouble(textT9)){
                                         //   check our ingrient weigth is enougth size pan or no
                                         if(pansizing<=Double.parseDouble(pan.getSize())){
                                         //   if good chack is true
                                             check=true;
                                        }   
                                        } }}}}}}}

                                    }

                                    if(check)
                                    {
                          
                                        if("Small".equals(size))
        { 
           // if small count+1 of selected size pizza
            pizza.setsmall(pizza.getsmall()+1);
        }
        if("Meduim".equals(size)){  pizza.setmeduim(pizza.getmeduim()+1);

        }
        if("Large".equals(size)){
  pizza.setlarge(pizza.gettlarge()+1);
        }
    //    when we complete cook pizza 
            //    ننقص الكمية من المخزن
                                        cheese.setWeight(cheese.getWeight()-Double.parseDouble(textT1));
                                        salt.setWeight(  salt.getWeight()-Double.parseDouble(textT2));
                                        flour.setWeight(flour.getWeight()-Double.parseDouble(textT3));
                                        yeast.setWeight( yeast.getWeight()-Double.parseDouble(textT4));
                                        Tomatoes.setWeight(Tomatoes.getWeight()-Double.parseDouble(textT5));
                                        Garilic.setWeight(Garilic.getWeight()-Double.parseDouble(textT6));
                                        onion.setWeight(onion.getWeight()-Double.parseDouble(textT7));
                                        Sause.setWeight(Sause.getWeight()-Double.parseDouble(textT8));
                                        cOregano.setWeight(cOregano.getWeight()-Double.parseDouble(textT9));
//اذا حدث خطا بيطلع لطباخ
                                    }else JOptionPane.showMessageDialog(null,"Verifiy the ingrediants please.", "Warning", JOptionPane.ERROR_MESSAGE);
                                    // TODO add your handling code here:
                                            String size2=sizee2.getSelectedItem().toString();//size of pan
//pan and pizza if size 
 if (size.equals(size2))

                                    {
                                    JOptionPane.showMessageDialog(null," pan and dough are sutible size "+ "\n  cooked succecfully");
                                    
                                    }
                                     JOptionPane.showMessageDialog(null," pan and dough are  not sutible size ");
try 
{
 if (size.equals(size2)){}
}
    catch (InputMismatchException e) {
  System.out.println("Exception ");
}
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    
    
    
    
    
    
    
    
    private void cheesee1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheesee1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cheesee1ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void pansizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pansizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pansizeActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
Tomatoes.setAmountcol((18*Integer.parseInt(tomatoess1.getText()))/100);
onion.setAmountcol((40*Integer.parseInt(onionn1.getText()))/100);
cheese.setAmountcol((300*Integer.parseInt(cheesee1.getText()))/100);
Sause.setAmountcol((117*Integer.parseInt(sausee.getText()))/100);
flour.setAmountcol((364*Integer.parseInt(flourr1.getText()))/100);
yeast.setAmountcol((18*Integer.parseInt(yeastt.getText()))/100);
Garilic.setAmountcol((149*Integer.parseInt(gralicc1.getText()))/100);
double sumCal=Tomatoes.getAmountcol()+onion.getAmountcol()+cheese.getAmountcol()+Sause.getAmountcol()+flour.getAmountcol()+yeast.getAmountcol()+Garilic.getAmountcol();
JOptionPane.showMessageDialog(null, sumCal  + " kcal ");

    }//GEN-LAST:event_jButton4ActionPerformed

    private void sizeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sizeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Machine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Machine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Machine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Machine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
         

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Machine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JTextField cheesee;
    private javax.swing.JTextField cheesee1;
    private javax.swing.JTextField flourr;
    private javax.swing.JTextField flourr1;
    private javax.swing.JTextField gralicc;
    private javax.swing.JTextField gralicc1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField onionn;
    private javax.swing.JTextField onionn1;
    private javax.swing.JTextField oreganoo;
    private javax.swing.JTextField oreganoo1;
    private javax.swing.JPanel panin;
    private javax.swing.JTextField pansize;
    private javax.swing.JTextField saltt;
    private javax.swing.JTextField saltt1;
    private javax.swing.JTextField sausee;
    private javax.swing.JTextField sausee1;
    private javax.swing.JComboBox<String> sizee;
    private javax.swing.JComboBox<String> sizee1;
    private javax.swing.JComboBox<String> sizee2;
    private javax.swing.JTextField tomatoess;
    private javax.swing.JTextField tomatoess1;
    private javax.swing.JTextField yeastt;
    private javax.swing.JTextField yeastt1;
    // End of variables declaration//GEN-END:variables
}
